### ISSUE TITLE
Extension of distance calculation to two arrays

### ISSUE THREAD

**Issue by jkapila** [HajkD/philentropy#11]
Hey Hajk,

Really thanks for implementing these measures as a package in R.

I have a case where I want to use these distances for calculating distance between two different arrays. This is case where I want to use these *distances as feed for KNN implementations*. 

What I tried was by "rbind" the two data and the calculate distances and then removing the rows and columns by index. But this is very **hacky** way and is also **not at all scalable**. 

So is there a way I can use your package for my purpose in a **_more efficient_** way?

**Comment by jkapila** [comment]
Code snippet for what I attempted:
```{r}
distances <- function(X, Y=NULL, method = "euclidean", p = NULL, test.na = TRUE,
                      unit = "log", est.prob = NULL) {
  if (!is.null(Y)){
    
    # Combinig Rows to fetch to philentropy
    tt_df <- rbind(X,Y)
    tt_vec <- c(rep(TRUE,NROW(X)), rep(FALSE,NROW(Y)))
    
    tt_dist <- philentropy::distance(tt_df,method = method, p = p, 
                                     test.na = test.na, unit = unit, 
                                     est.prob = est.prob)
    tt_dist <- tt_dist[!tt_vec,tt_vec]
    class(tt_dist) = 'dist_mat'
    return(tt_dist)
  }else{
    tt_dist <- philentropy::distance(X,method = method, p = p, 
                                     test.na = test.na, unit = unit, 
                                     est.prob = est.prob)
    class(tt_dist) = 'dist_mat'
    return(tt_dist)
  }
  
}
```

**Comment by HajkD** [comment]
Hi @jkapila,

Thank you very much for your example code and sorry for my late response, I was on holidays.

I will have a look at it and see if I can speed it up.

I will keep you posted :)

Many thanks,
Hajk

**Comment by jkapila** [comment]
Any updates / plans on this @HajkD ..??

**Comment by HajkD** [comment]
Hi @jkapila,

Could you please provide me with a small working example of an input and output dataset as well as an example workflow that you are interested in?

I am sorry, but I am not sure what you mean when you say

>What I tried was by "rbind" the two data and the calculate distances and then removing the rows and columns by index.

Do you want to compute a distance matrix from an input matrix?

For example, you could do the following:

```r
## compute the euclidean distance between all pairwise comparisons of probability vectors
ProbMatrix <- rbind(1:10/sum(1:10), 20:29/sum(20:29),30:39/sum(30:39))
distance(ProbMatrix, method = "euclidean")
```

```
Metric: 'euclidean'; comparing: 3 vectors.
          v1         v2         v3
v1 0.0000000 0.12807130 0.13881717
v2 0.1280713 0.00000000 0.01074588
v3 0.1388172 0.01074588 0.00000000
```

In case I misunderstood you, please specify in greater detail why you want to `remove the rows and columns by index` and which rows and columns you want to remove?

Without a very detailed example and more specifications on what you would like to do, I am a bit left with guesswork.

Let me know if this helps.

Cheers,
Hajk

**Comment by surmann** [comment]
Hallo Hajk!

I have the same issue. Currently, I solve it with the package `SpatialTools`. However, there are not that many distances available than in your package.
Here is my current implementation. I want to know all distances between `x` and all points in `y`.

    x = matrix(rnorm(50), ncol = 50)
    y = matrix(rnorm(50*1000), ncol = 50)
    SpatialTools::dist2(x, y)

To the the same result in `philentropy` you have to write

    apply(y, 1, philentropy::euclidean, x, testNA = FALSE)

Unfortunately, this is 10 times slower than `SpatialTools`:

    microbenchmark(SpatialTools::dist2(x, y), apply(y, 1, philentropy::euclidean, x, testNA = FALSE))

Does this help?

All best,
Dirk

**Comment by HajkD** [comment]
Hi Dirk,

Many thanks for this great comment and example. 

So far, I implemented `philentropy` with the sole intention to be able to compare two or multiple distributions with each other. So the functions are not optimized to compare individual points with entire distributions or multidimensional vectors. 

Let me see how I can implement something similar to the `SpatialTools` function. If you have any further ideas on this (since you seem to work more closely with these type of anayses) then I would truly appreciate it and it would allow me to speed up the implementation process.

Many thanks and I look forward to working with you on this :)

Cheers,
Hajk

**Comment by surmann** [comment]
Hallo Hajk,

you're welcome.

For my analysis I need distances between all vectors in a matrix and a vector. This is not the standard case as `stats::dist` etc. don't take it into account.
Do you have any specific questions to implement this?

All best
Dirk
