### ISSUE TITLE
Compatibility with hclust

### ISSUE THREAD

**Issue by ChrisNeefus** [HajkD/philentropy#13]
First, thank for creating the package. Distance measure option had been quite limited. 
My issue is that the distance matrix built by distance() doesn't seem to be compatible with hclust.  If I display the matrix, it looks fine, but when I ask hclust to cluster it I get:
Error in if (is.na(n) || n > 65536L) stop("size cannot be NA nor exceed 65536") : 
  missing value where TRUE/FALSE needed
So this works fine
dist.mat<-dist(birds.t,method="jaccard")
clust.res<-hclust(dist.mat,method="complete")
but this does not
dist.mat<-distance(birds.t,method="jaccard")
clust.res<-hclust(dist.mat,method="complete")

One other request - it would be great if the distance matrix automatically used the row labels from the data.frame for its row and column labels.

**Comment by HajkD** [comment]
Hi Chris,

Many thanks for contacting me and for pointing out this limitation.

I will have a look at this and will come back to you soon.

Your feedback is highly appreciated :-)

Cheers,
Hajk

**Comment by Nowosad** [comment]
@ChrisNeefus ,
I think you need to convert the `distance()` output to `dist` first:

```r
dist.mat <- distance(birds.t, method = "jaccard")
true.dist.mat <- as.dist(dist.mat)
clust.res <- hclust(true.dist.mat, method = "complete")
```

**Comment by HajkD** [comment]
Hi @Nowosad,

Thank you so much for clarifying this. You are absolutely correct.

This trick should resolve this issue.

Many many thanks and kind wishes,
Hajk

**Comment by Nowosad** [comment]
Thanks for the package @HajkD !
