### ISSUE TITLE
compatibility with data.table

### ISSUE THREAD

**Issue by benmiller314** [HajkD/philentropy#16]
I have a [`data.table`](https://cran.r-project.org/web/packages/data.table/data.table.pdf) of probability vectors among which to compute distances. The `distance()` function is throwing an error early on:

```
if (!is.element(class(x), c("data.frame", "matrix")))
    stop("x should be a data.frame or matrix.")
```

But a `data.table` **is** a `data.frame`: `class(DT)` returns `c("data.table", "data.frame")`. Can you update the logic to allow for multiple classes in `x`? I haven't tested to see if something as simple as wrapping the above condition if `any()` would work... but maybe?

**Comment by benmiller314** [comment]
In the meantime, it's not a burning problem, because I can always just make it explicit with `as.data.frame(DT)`. But I was confused for a while and thought I'd somehow un-data-tabled my data, when I hadn't.

**Comment by HajkD** [comment]
Hi Ben,

Many thanks for making me aware of this issue. I now added an `any()` check 
and also included `data.table` and `tibble` as options.

Let me know if it works for you now.

Best wishes,
Hajk
