### ISSUE TITLE
make `distance()` more like `dist()`

### ISSUE THREAD

**Issue by tavareshugo** [HajkD/philentropy#18]
Hi @HajkD ,

firstly, thanks so much for this very convenient package! :smiley: 

I was  just wondering if `distance()` could make output more like `dist()` function (unless there was a design reason to do it otherwise?). Namely, two things (not mutually exclusive):

- make it such that `distance()` outputs an object of class "dist" (or have an option to do so?)
- make it such that _rownames_ attribute of input matrix is not lost

It can be worked around (this was mentioned in #13), but I guess it might make coding a bit easier to effortlessly feed into other functions that expect `dist`-type input. 

```r
# for example this can be fed directly to `hclust()`
dist1 <- dist(mtcars) 

# this needs some processing
dist2 <- distance(mtcars)
rownames(dist2) <- colnames(dist2) <- rownames(mtcars)
dist2 <- as.dist(dist2)
```

As a side effect, I think "`dist`" objects may be smaller as well, which may be a plus for very large data.

**Comment by HajkD** [comment]
Hi Hugo,

I hope you are doing well? Many thanks for this request.

Just to clarify, would you prefer something like:

```r
# as output of the distance() function 
return(as.dist(dist))
# rather than
return(dist)
```

Or would you prefer to have a custom S3 or S4 class that stores the distance matrix output and which also inherits from the native R `dist()` class?

Regarding the `rownames`, that's no problem at all and I am happy to adjust this.

Many thanks for your feedback and I very much look forward to hearing from you.

Cheers,
Hajk

**Comment by tavareshugo** [comment]
Hi @HajkD ,

Firstly, I just noticed there's an option `use.row.names` in your development version (not the one I installed from CRAN, v0.3.0), so I guess that's taken care of. 

I don't think a custom class would be needed, so like you suggested, just also perhaps add attribute with the method used (to fully mimic `stats::dist()`, so:

```r
dist <- as.dist(dist)
attr(dist, "method") <- method
return(dist)
```

The problem is that if you make this the default, then it might break some people's code that are using your functions, since the output would not be a matrix but a "dist" object.

**Comment by HajkD** [comment]
Hi Hugo,

absolutely excellent! Thank you very much for this example and for the clarification.

I now added another argument to `philentropy::distance()` named `as.dist.obj` (default `FALSE`) which allows users to return a `stats::dist` object if they wish. In combination with `use.row.names` your extension request should be possible now.

Example:

```r
# construct example input matrix
ProbMatrix <- rbind(1:10/sum(1:10), 20:29/sum(20:29),30:39/sum(30:39))
distance(ProbMatrix, method = "euclidean", as.dist.obj = TRUE)
```

```
Metric: 'euclidean'; comparing: 3 vectors.
           v1         v2
v2 0.12807130           
v3 0.13881717 0.01074588
```

And with `use.row.names = TRUE`:

```r
ProbMatrix <- rbind(1:10/sum(1:10), 20:29/sum(20:29),30:39/sum(30:39))
rownames(ProbMatrix) <- paste0("test", 1:3)
distance(ProbMatrix, method = "euclidean", use.row.names = TRUE, as.dist.obj = TRUE)
```

```
Metric: 'euclidean'; comparing: 3 vectors.
           test1      test2
test2 0.12807130           
test3 0.13881717 0.01074588
```

The `mtcars` dataset includes only characters as columns and thus I don't feel comfortable to give users too much flexibility when guessing how to convert "character numerics" into numerics.

```r
apply(mtcars, 2, class)
```

```
        mpg         cyl        disp          hp        drat          wt 
"character" "character" "character" "character" "character" "character" 
       qsec          vs          am        gear        carb 
"character" "character" "character" "character" "character" 
```

Does this solve all the issues?

I hope this helps?

Many thanks!

**Comment by tavareshugo** [comment]
@HajkD , that's super! It's indeed working as I was thinking about :smiley: 
Feel free to close the issue, and thanks so much for the addition!

(ps - not sure what's up with your `mtcars` dataset, all columns should be numeric)

**Comment by HajkD** [comment]
@tavareshugo , brilliant! Many thanks for your request and feedback and I am happy that everything works now.

(ps - lol... I indeed have to find out what happened to my `mtcars` dataset!!!)
