### ISSUE TITLE
question about function ‘bhattacharyya‘ in philentropy

### ISSUE THREAD

**Issue by MMriran** [HajkD/philentropy#21]
Hi， thank you for your great work on philentropy, it is really useful for us and I had a question to ask.

    I uesed the function ‘bhattacharyya‘ to calculate the Bhattacharyya distance on my own data and then get a negative value.  And according to the formula, the value should be 0≤ BD <∞, is there anything wrong?

**Comment by HajkD** [comment]
Hi @MMriran,

Many thanks for contacting me and I am very happy to hear that you find `philentropy` useful for your research.

Would it be possible that you construct a little example for me that I can then troubleshoot?

This will speed up the process of debugging or helping figure out what is going on.

Many thanks,
Hajk

**Comment by MMriran** [comment]
Thank you  for your reply.  I really appreciate your help!

[testdata.zip](https://github.com/HajkD/philentropy/files/4255197/testdata.zip)

**Comment by MMriran** [comment]
Thank you for your reply.The code for   was ‘distance(x,method="bhattacharyya") ’. I really appreciate your help!  
[testdata.zip](https://github.com/HajkD/philentropy/files/4255227/testdata.zip)

**Comment by HajkD** [comment]
Could you please construct a small dummy example analogous to this one?

```r
philentropy::distance(rbind(c(0.2,0.1,0.7), c(0.3, 0.3, 0.4), c(0.2, 0.8, 0)), method = "bhattacharyya")
```

```
Metric: 'bhattacharyya' using unit: 'log'; comparing: 3 vectors.
           v1         v2        v3
v1 0.00000000 0.05413489 0.7280643
v2 0.05413489 0.00000000 0.3080931
v3 0.72806433 0.30809307 0.0000000
```

In your case, is the sum of each input vector `1`?

Thanks!

**Comment by MMriran** [comment]
Hi, thank you for your reply. I had checked my data and the the sum of each input vector is not equal to 1.  Is the sum of each input vector should be 1？

**Comment by HajkD** [comment]
Yes, this is the assumption of a probability vector. The `philentropy` package computes distances between probability vectors (= probability distributions).

I hope this helps.

**Comment by MMriran** [comment]
got it！ thank your for your help！:)
