### ISSUE TITLE
typo in JSD() help

### ISSUE THREAD

**Issue by wkc1986** [HajkD/philentropy#5]
> \# Example: Distance Matrix using JSD-Distance
> `Prob <- cbind(1:10/sum(1:10), 20:29/sum(20:29), 30:39/sum(30:39))`

This states that columns should be distributions in the input matrix, but the function uses the rows as distributions.

**Comment by HajkD** [comment]
Dear @wkc1986 

This is absolutely correct!

This is clearly a typo :)

I now fixed it and also fixed the corresponding copy/paste typos in `gJSD()` and the Vignette examples.

Many many thanks for pointing this out to me.

This really helps a lot :)

Best wishes,
Hajk
