### ISSUE TITLE
Please confirm the journal for this citation

### ISSUE THREAD

**Issue by leeper** [HajkD/philentropy#6]
I'm not sure this is the correct journal name: https://github.com/HajkD/philentropy/blob/master/paper.bib#L4

**Comment by leeper** [comment]
The journal appears to have a different title according to the PDF (http://csis.pace.edu/ctappert/dps/d861-12/session4-p2.pdf), specifically the journal listed here: http://www.naun.org/main/NAUN/ijmmas/2007.htm. I think the Google Scholar citation is an error and it should be International Journal of Mathematical Models and Methods in Applied Science.

**Comment by HajkD** [comment]
Dear @leeper,

Thank you so much for doing the research. I revised the reference accordingly and pushed in to GitHub.

I hope everything else looks fine now?

Kind regards,
Hajk
