### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by kellieotto** [HajkD/philentropy#8]
This is detailed feedback for your JOSS review openjournals/joss-reviews#765.

I see that your code and DESCRIPTION contain GPL license info. This is great. JOSS requires you to have a plain-text LICENSE file, in your main repository, with the contents of your chosen software license.

**Comment by HajkD** [comment]
Dear Kellie,

Many thanks for making me aware of the missing license. 
I now added a GLP-2 license file according to JOSS policy.

Kind regards,
Hajk
